In [4]:

import pandas as pd
df = pd.read_excel('./assets/data_preprocess.xlsx')
print(df)
# 데이터 분석:
# 2번 행의 age가 NaN(결측치)
# 8번 행의 address가 NaN(결측치)
# 6번 행의 age의 값이 비정상적으로 높음(이상치)
# 3번행과 7번행이 동일(중복값)


df_modi = df.drop(7) # 7번 행 삭제
# df_modi = df.dro  중복 자동 삭제
df_modi.dropna(inplace=True) # NaN이 포함된 행 제거
df_modi.loc[6, 'age']=18
df_modi
# print(df_modi.iloc[6, 3])
print(df_modi.dropna(how='any'))

       name    age   address            job
0   Jackson   27.0   Gangwon          Sales
1     Lucas   15.0     Seoul   Student(mid)
2       Mia    NaN    Sejong       Cashiers
3   Abigail   24.0     Busan        Waiters
4     James   28.0      Jeju        Analyst
5  Benjamin   34.0  Gyeonggi       Cashiers
6   William  180.0     Ulsan  Student(high)
7   Abigail   24.0     Busan        Waiters
8     Emily   31.0       NaN         Driver
9     Henry   43.0     Daegu         Doctor
       name   age   address            job
0   Jackson  27.0   Gangwon          Sales
1     Lucas  15.0     Seoul   Student(mid)
3   Abigail  24.0     Busan        Waiters
4     James  28.0      Jeju        Analyst
5  Benjamin  34.0  Gyeonggi       Cashiers
6   William  18.0     Ulsan  Student(high)
9     Henry  43.0     Daegu         Doctor

In [5]:
df_col1 = df_modi['name']
print(df_col1)
print(type(df_col1))

df_col2 = df_modi[['age']]
print(df_col2)
print(type(df_col2))

0     Jackson
1       Lucas
3     Abigail
4       James
5    Benjamin
6     William
9       Henry
Name: name, dtype: str
<class 'pandas.Series'>
    age
0  27.0
1  15.0
3  24.0
4  28.0
5  34.0
6  18.0
9  43.0
<class 'pandas.DataFrame'>

In [6]:
df = pd.read_excel('./assets/data_preprocess.xlsx')
df.dropna()

       name    age   address            job
0   Jackson   27.0   Gangwon          Sales
1     Lucas   15.0     Seoul   Student(mid)
3   Abigail   24.0     Busan        Waiters
4     James   28.0      Jeju        Analyst
5  Benjamin   34.0  Gyeonggi       Cashiers
6   William  180.0     Ulsan  Student(high)
7   Abigail   24.0     Busan        Waiters
9     Henry   43.0     Daegu         Doctor

In [7]:
# 행 선택
print(df_modi.loc[3])
print(type(df_modi.loc[3]))
print(df_modi.iloc[3])

name       Abigail
age           24.0
address      Busan
job        Waiters
Name: 3, dtype: object
<class 'pandas.Series'>
name         James
age           28.0
address       Jeju
job        Analyst
Name: 4, dtype: object

In [8]:
df_modi['age'] = df_modi['age'].astype(int)
df.head()

      name   age  address           job
0  Jackson  27.0  Gangwon         Sales
1    Lucas  15.0    Seoul  Student(mid)
2      Mia   NaN   Sejong      Cashiers
3  Abigail  24.0    Busan       Waiters
4    James  28.0     Jeju       Analyst

In [ ]:
## 데이터 전처리 3

In [10]:
df_modi.sort_values(by='name', ascending=True, inplace=True)
print(df_modi)

       name  age   address            job
3   Abigail   24     Busan        Waiters
5  Benjamin   34  Gyeonggi       Cashiers
9     Henry   43     Daegu         Doctor
0   Jackson   27   Gangwon          Sales
4     James   28      Jeju        Analyst
1     Lucas   15     Seoul   Student(mid)
6   William   18     Ulsan  Student(high)